# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteadmin',
            name='role',
            field=models.CharField(default='', max_length=64, verbose_name='权限'),
        ),
    ]
